fix: `ListGroups` request V3
Currently, the v3 version of this request is lacking `tagged_fields`.

```
[2025-07-25 13:35:23,014] ERROR Exception while processing request from 172.100.239.7:9092-172.100.239.2:41464-502 (kafka.network.Processor)
org.apache.kafka.common.errors.InvalidRequestException: Error getting request for apiKey: LIST_GROUPS, apiVersion: 3, connectionId: 172.100.239.7:9092-172.100.239.2:41464-502, listenerName: ListenerName(PLAINTEXT), principal: User:ANONYMOUS
Caused by: java.nio.BufferUnderflowException
	at java.base/java.nio.Buffer.nextGetIndex(Unknown Source)
	at java.base/java.nio.HeapByteBuffer.get(Unknown Source)
	at org.apache.kafka.common.utils.ByteUtils.readUnsignedVarint(ByteUtils.java:146)
	at org.apache.kafka.common.protocol.ByteBufferAccessor.readUnsignedVarint(ByteBufferAccessor.java:63)
	at org.apache.kafka.common.message.ListGroupsRequestData.read(ListGroupsRequestData.java:129)
	at org.apache.kafka.common.message.ListGroupsRequestData.<init>(ListGroupsRequestData.java:80)
	at org.apache.kafka.common.requests.ListGroupsRequest.parse(ListGroupsRequest.java:81)
	at org.apache.kafka.common.requests.AbstractRequest.doParseRequest(AbstractRequest.java:190)
	at org.apache.kafka.common.requests.AbstractRequest.parseRequest(AbstractRequest.java:152)
	at org.apache.kafka.common.requests.RequestContext.parseRequest(RequestContext.java:95)
	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:102)
	at kafka.network.Processor.$anonfun$processCompletedReceives$1(SocketServer.scala:1030)
	at java.base/java.util.LinkedHashMap$LinkedValues.forEach(Unknown Source)
	at kafka.network.Processor.processCompletedReceives(SocketServer.scala:1008)
	at kafka.network.Processor.run(SocketServer.scala:893)
	at java.base/java.lang.Thread.run(Unknown Source)
```