Causes a connection reset when unknown_topic_or_partition error happens.
According to the Kafka Protocol documentation, this is a retriable error:
https://kafka.apache.org/protocol#protocol_error_codes
Error: UNKNOWN_TOPIC_OR_PARTITION
Code: 3
Retriable: True
Description: This server does not host this topic-partition.

This is unlike invalid_topic_exception which is not retriable.